### ISSUE TITLE
The `create_basemap` does not support `kwargs_dict` argment.

### ISSUE THREAD

**Issue by i-aki-y** [Solafune-Inc/solafune-tools#2]
In the readme example, create_basemap uses `kwargs_dict`, but it does not appear to support the `kwargs_dict` argument.

```py
mosaics_catalog = solafune_tools.create_basemap(
    start_date="2023-05-01",
    end_date="2023-08-01",
    aoi_geometry_file="data/geojson/xyz_bounds.geojson",
    kwargs_dict={"eo:cloud_cover": {"lt": 10}, "s2:nodata_pixel_percentage": {"lt":20}},
    bands="Auto",
    mosaic_epsg="Auto",
    mosaic_resolution=100,
    clip_to_aoi=True,
)
```

https://github.com/Solafune-Inc/solafune-tools/blob/87694012c4bbbe2bca6d15296d9022e4f2a50354/solafune_tools/pipeline.py#L8-L18

**Comment by pkopparla** [comment]
Thank you for the report, this is indeed a bug.
